-- Seed: Pat Busch Mountain Reserve + demo wedding
-- Generated by scripts/generate_seed_sql.mjs from reference/assets/app.js
-- Idempotent: uses ON CONFLICT DO NOTHING on the venue/wedding rows.

insert into venues (id, slug, name, region, contact_email, branding_primary, subscription_status, trial_ends_at)
values ('11111111-1111-1111-1111-111111111111', 'pat-busch', 'Pat Busch Mountain Reserve', 'Robertson, Western Cape', 'info@patbusch.co.za', '#0a4a3a', 'trialing', now() + interval '14 days')
on conflict (id) do nothing;

insert into weddings (id, venue_id, slug, couple_names, wedding_date, guest_count, status, total_budget, notes)
values ('22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111111', 'demo-wedding', 'Heather & Mark', '2027-01-07', 120, 'in_planning', 250000, 'Demo wedding seeded from Pat Busch reference HTML.')
on conflict (id) do nothing;

-- Clear prior seeds so this script is rerunnable.
delete from catalogue_items     where venue_id = '11111111-1111-1111-1111-111111111111';
delete from rental_items        where venue_id = '11111111-1111-1111-1111-111111111111';
delete from accommodation_rooms where venue_id = '11111111-1111-1111-1111-111111111111';
delete from suppliers           where wedding_id = '22222222-2222-2222-2222-222222222222';
delete from timeline_items      where wedding_id = '22222222-2222-2222-2222-222222222222';

-- Catalogue (included with venue rental)

insert into catalogue_items (venue_id, category, name, description, price, price_unit, sort_order) values
('11111111-1111-1111-1111-111111111111', 'Glassware & Serveware', 'Champagne Flutes, Wine & Beer Glasses', '200× Champagne Flutes, Universal Wine glasses (red & white), Willy Beer glasses & Zombie glasses. Sufficient for all areas for up to 120 guests.', 0, 'fixed', 0),
('11111111-1111-1111-1111-111111111111', 'Glassware & Serveware', 'White Dinner Plates, Side Plates & Soup Bowls', '120× Marola broad-rim white catering crockery — formal wedding stock, all matching. Farmhouse Erika has its own informal crockery which does not match.', 0, 'fixed', 1),
('11111111-1111-1111-1111-111111111111', 'Glassware & Serveware', 'White Coffee / Tea Mugs', '70–100× Straight-sided catering mugs, no saucer. For Farewell Breakfast, late-night tea/coffee & hot chocolate station.', 0, 'fixed', 2),
('11111111-1111-1111-1111-111111111111', 'Glassware & Serveware', 'Dinner Cutlery & Salt & Pepper Shakers', '120× Dinner Knives, Forks, Dessert Spoons, Teaspoons & Cake Forks (Munich style stainless steel) — formal wedding cutlery. Plus 30 Salt & Pepper shaker sets.', 0, 'fixed', 3),
('11111111-1111-1111-1111-111111111111', 'Glassware & Serveware', 'Champagne Bowls & Ice Buckets (Large)', '2× XL ice buckets/bowls + 1× upright bucket. Large steel ice bowls — great for white wine, champagne, ice, beers & ciders.', 0, 'fixed', 4),
('11111111-1111-1111-1111-111111111111', 'Glassware & Serveware', 'Jugs, Carafes & Ashtrays', '15× variety of Water Jugs, Vintage Juice Jugs & Carafes — enough for all tables. Great for punch, water, juices & iced tea. Plus glass & ceramic ashtrays.', 0, 'fixed', 5),
('11111111-1111-1111-1111-111111111111', 'Glassware & Serveware', 'Ice Buckets — Stainless Steel (various)', 'Variety of SS ice buckets from large 5L with handles to smaller sizes. For ice on tables, at the bar, or chilling white wine & beers.', 0, 'fixed', 6),
('11111111-1111-1111-1111-111111111111', 'Glassware & Serveware', 'Sundry Bar & Wedding Cake Utensils', 'Ice tongs, waiters'' friends, serving spoons, wedding cake lifter & knife set. Catering-grade serving items for bar, harvest & buffet tables.', 0, 'fixed', 7),
('11111111-1111-1111-1111-111111111111', 'Glassware & Serveware', 'Wood Platters & Boards', '16× variety of Oak Barrel Head platters with rope handles, Oval Long Platters & Rectangular wood platters. Great for harvest table, cheese boards, pizzas & breads.', 0, 'fixed', 8),
('11111111-1111-1111-1111-111111111111', 'Décor & Display', 'Rustic Cake Stands & Fly Chasers', 'Wood tree-slice rustic cake stands on stands. Battery-operated swirling fly chasers for harvest table.', 0, 'fixed', 9),
('11111111-1111-1111-1111-111111111111', 'Kitchen & Braai', 'Cast-Iron Potjie Pots, Braai Grids & Utensils', '1× full set: Variety of No.3 to No.14 XXL cast-iron rounded potjie pots (small to HUGE), flat-bottomed pots, braai grids, braai tongs, braai spades, wooden spoons, etc. For M&G catering, potjie competitions & large-group braais.', 0, 'fixed', 10),
('11111111-1111-1111-1111-111111111111', 'Rustic Vessels', 'Galvanised Metal Rustic Buckets', '20+ galvanised metal buckets with handles — Small, Medium & Large. Weathered metal patina. Great as rustic ice buckets for drinks, or for flowers & confetti. Not for ice used in drinks.', 0, 'fixed', 11),
('11111111-1111-1111-1111-111111111111', 'Rustic Vessels', 'Half Oak Barrels — Round (with tub liners)', '5× half oak barrels cut across width, round. Includes tub liners to prevent leaking. For cooling "help-yourself" drinks stacked high with ice, flowers & décor, or turned over as coffee tables.', 0, 'fixed', 12),
('11111111-1111-1111-1111-111111111111', 'Rustic Vessels', 'Half Oak Barrel — Oval (with rope handles)', '2× half oak barrels cut lengthwise, oval-shaped with rope handles. Great for décor, flowers, confetti, umbrellas, breads, gifts, or transporting drinks.', 0, 'fixed', 13),
('11111111-1111-1111-1111-111111111111', 'Rustic Vessels', 'Wheel Barrows — Rustic & Patinaed', '2× rustic patinaed wheelbarrows. For transporting drinks or as rustic wedding décor — great for presenting mineral waters on ice at the ceremony or help-yourself iced beers & ciders.', 0, 'fixed', 14),
('11111111-1111-1111-1111-111111111111', 'Tables & Seating', 'Dinner Tables — Pine Whitewashed', '15× Pine whitewashed wedding tabletops (2.5m × 0.9m) on dark-stained trestle legs. For the reception dinner tables or elsewhere.', 0, 'fixed', 15),
('11111111-1111-1111-1111-111111111111', 'Tables & Seating', 'Kids Tables — Chalkboard Tabletops', '2× fun chalkboard tabletops for kids to eat at and draw on. Usually set up on straw bales — chalk supplied in a jar.', 0, 'fixed', 16),
('11111111-1111-1111-1111-111111111111', 'Tables & Seating', 'Pine White-Washed Ceremony Benches', '30× pine whitewashed ceremony benches with darker stained legs. For ceremony seating on level ground, seating at trestle tables, or around fire baskets & lounges.', 0, 'fixed', 17),
('11111111-1111-1111-1111-111111111111', 'Tables & Seating', 'Extra Tables — Slatted Pine (white)', '4× slatted pine tabletops (2.4m × 0.75m, white). For buffet tables, bar tops, harvest tables, display & décor, cake table, satellite bar, etc.', 0, 'fixed', 18),
('11111111-1111-1111-1111-111111111111', 'Tables & Seating', 'Harvest Tabletops — Extra Large', '2× very large harvest tabletops (3m × 1.2m) — one stained pine, one white. For harvest tables, buffet tables or bar tops. Usually set up on two oak barrels (bar height).', 0, 'fixed', 19),
('11111111-1111-1111-1111-111111111111', 'Tables & Seating', 'Extra Tables — Oregon Pine, Teak Square & Rectangular', '10× variety: Oregon Pine Square Tables (90×90cm), Teak Square café tables (90×90cm), Teak Rectangular Tables (150×95cm). For DJ, cake, décor, gifts, drinks station, coffee & tea setup, memory table, etc.', 0, 'fixed', 20),
('11111111-1111-1111-1111-111111111111', 'Tables & Seating', 'Rustic Coffee Tables from Reclaimed Pallet Wood', '5× rustic coffee tables (1m × 0.9m). For lounge pockets at pre-drinks, near fire baskets, or for lawn games.', 0, 'fixed', 21),
('11111111-1111-1111-1111-111111111111', 'Barrels & Crates', 'Oak Wine Barrels — Full Size', '10× full-size oak barrels (90cm high). For building bars, placing harvest tabletops on, general décor, ad-hoc tables, flowers, ceremony aisle ends, lawn games, etc.', 0, 'fixed', 22),
('11111111-1111-1111-1111-111111111111', 'Barrels & Crates', 'Harvest Bin / Pallet Apple Crates', '5× raw wood + 4× white-washed harvest bin crates. For building rustic satellite bars, harvest tables, or extending existing bars.', 0, 'fixed', 23),
('11111111-1111-1111-1111-111111111111', 'Soft Décor & Fabric', 'White Fabric Satin Draping — 7m', '1× long white satin draping for the oak tree, wrapped around the wedding arch, or ceremony use, etc.', 0, 'fixed', 24),
('11111111-1111-1111-1111-111111111111', 'Soft Décor & Fabric', 'White Flagged Bunting — approx 100m', '1× set of various triangular white flagged bunting pieces which can be joined. Creates a festive festival atmosphere, or cordons off areas.', 0, 'fixed', 25),
('11111111-1111-1111-1111-111111111111', 'Signage & Chalkboards', '"Cheers", "Mr & Mrs" Signs & Cutout Letters', '1× "Cheers" sign on board, 1× "Mr & Mrs" sign on board, plus larger "Mr" & "Mrs" cutout loose letters (approx 25cm high).', 0, 'fixed', 26),
('11111111-1111-1111-1111-111111111111', 'Rustic Vessels', 'Vintage Galvanised Watering Can & Milk Can', '1× large vintage galvanised watering can + 1× large galvanised milk can, both rustic patinaed metal. For general décor or flowers.', 0, 'fixed', 27),
('11111111-1111-1111-1111-111111111111', 'Signage & Chalkboards', 'Rustic Wood Step Ladder — Small', '1× small rustic wood step ladder with vintage patina. Great for displaying blankets & throws, seating plans, welcome drinks stand, cocktail display, or general décor.', 0, 'fixed', 28),
('11111111-1111-1111-1111-111111111111', 'Signage & Chalkboards', 'White-Washed Framed Chalkboard', '2× white-washed framed chalkboards (93×62cm board, 120×90cm with frame). For menus, seating plans, timeline, DJ lineup, cocktails, wedding poetry, etc.', 0, 'fixed', 29),
('11111111-1111-1111-1111-111111111111', 'Signage & Chalkboards', 'Rustic Pine Framed Chalkboard (Natural)', '1× rustic natural pine framed chalkboard (111×61cm board). For menus, seating plans, timeline, schedule, poetry, DJ lineup, cocktails, etc.', 0, 'fixed', 30),
('11111111-1111-1111-1111-111111111111', 'Frames, Easels & Mirrors', 'Painted Framed Mirrors — Large on Easel', '2× large painted framed mirrors, usually placed on easels wherever the Bride & Groom are getting ready. Also used as décor or signage.', 0, 'fixed', 31),
('11111111-1111-1111-1111-111111111111', 'Signage & Chalkboards', 'Ornate Gilded Framed Chalkboard', '1× beautiful ornately gilded framed chalkboard on stand (80×143cm). For menus, seating plans, quotes, etc. — chalk supplied. Perfect at the entrance to reception or ceremony.', 0, 'fixed', 32),
('11111111-1111-1111-1111-111111111111', 'Frames, Easels & Mirrors', 'Large Stained Wood "Photo" Frame', '1× large stained wood photo frame. Hung on poles at pre-drinks or reception — great for guests to pose behind, or to frame the mountain view.', 0, 'fixed', 33),
('11111111-1111-1111-1111-111111111111', 'Frames, Easels & Mirrors', 'Easels — Whitewashed Wood, Large Floorstanding', '4× large whitewashed wood floorstanding easels. For chalkboards, mirrors, seating plans, DJ line-ups, menus, schedule of events, etc.', 0, 'fixed', 34),
('11111111-1111-1111-1111-111111111111', 'Signage & Chalkboards', 'Smaller A4 Chalkboards in Wood Frame', '8× various A4-sized chalkboards in wood frames. For signage, menus, quirky one-liners, harvest table display, cocktail ingredients, etc.', 0, 'fixed', 35),
('11111111-1111-1111-1111-111111111111', 'Baskets & Rustic Décor', 'Sundry Wood Crates (Jonkeer, Coca Cola & Bashews)', '6× various wood crates. For décor, stacked display, storage & transport, flower or gift crates, or to build levels on the harvest table.', 0, 'fixed', 36),
('11111111-1111-1111-1111-111111111111', 'Baskets & Rustic Décor', 'Woven Cane & Harvest Baskets', '4× large & small woven baskets (round & square). For décor, flowers, confetti, cooldrinks, umbrellas, blankets, throws, breads, fruits, etc.', 0, 'fixed', 37),
('11111111-1111-1111-1111-111111111111', 'Baskets & Rustic Décor', 'Rustic Wooden Log Arch (180×200cm)', '1× rustic wooden log arch. Used at the ceremony area draped with cloth, macramé or flowers. Also as general décor or prop.', 0, 'fixed', 38),
('11111111-1111-1111-1111-111111111111', 'Baskets & Rustic Décor', 'Wood Branch Blocks — Name / Card Holders', '100× wood branch blocks with slot for names, menus, cocktail cards, etc. Bring your own cards to slide into the slot.', 0, 'fixed', 39),
('11111111-1111-1111-1111-111111111111', 'Signage & Chalkboards', 'Rustic Wooden Pallet Chalkboard', '1× rustic wooden pallet chalkboard for signage, directional info, menus, DJ lineup, Happy Hour, etc.', 0, 'fixed', 40),
('11111111-1111-1111-1111-111111111111', 'Baskets & Rustic Décor', 'Hearts — Chalkboard & Woven Twig Hearts', '2× white-washed heart-shaped chalkboard hearts, plain chalkboard hearts & woven hearts of twigs & branches. For signage or décor.', 0, 'fixed', 41),
('11111111-1111-1111-1111-111111111111', 'Baskets & Rustic Décor', 'Slender Metal Bird Cages — Black', '3× slender black metal bird cages. Hanging décor from trees or on tables — can hold tealight candles in the evening.', 0, 'fixed', 42),
('11111111-1111-1111-1111-111111111111', 'Frames, Easels & Mirrors', 'Tabletop Easels — Blackwood, Pine & White Metal', '5× variety of tabletop easels. For menus, cocktails, notices, seating plans, DJ info, or holding smaller framed chalkboards.', 0, 'fixed', 43),
('11111111-1111-1111-1111-111111111111', 'Signage & Chalkboards', 'Signage Stand Sets', '2× signage stands — one rustic trellis poles with chalkboard signs, one with neat printed signs on a wood stand. Directional & fun, to show guests where to go.', 0, 'fixed', 44);

-- Rentals

insert into rental_items (venue_id, category, name, description, price, stock_total, sort_order) values
('11111111-1111-1111-1111-111111111111', 'Catering & Beverages', 'Basic DIY Coffee & Tea Station', 'Urn, mugs, instant coffee, Ceylon & Rooibos, hot chocolate, milk, sweeteners, sugar', 850, 1, 0),
('11111111-1111-1111-1111-111111111111', 'Catering & Beverages', 'Gourmet DIY Coffee & Tea', 'Percolator rental R400 + R600/brew (~50 cups) incl. Tea Station setup', 1000, 1, 1),
('11111111-1111-1111-1111-111111111111', 'Catering & Beverages', 'Gourmet Bean-to-Cup Jura X8 Coffee', '+ R25 per cup. Full Tea Station. Breakfast setup only.', 1000, 1, 2),
('11111111-1111-1111-1111-111111111111', 'Catering & Beverages', 'Hot Water Urn (Large)', 'Incl. S/S & Plastic drip tray', 200, 1, 3),
('11111111-1111-1111-1111-111111111111', 'Catering & Beverages', 'Coffee Percolator', 'Incl. internal flute & basket', 400, 1, 4),
('11111111-1111-1111-1111-111111111111', 'Catering & Beverages', 'Cake Lifter & Knife Set — Ornate', 'Upmarket set for wedding cake', 50, 1, 5),
('11111111-1111-1111-1111-111111111111', 'Outdoor & Décor', 'Café Parasols (2.5×2.5m)', 'Incl. bases — each', 250, 13, 6),
('11111111-1111-1111-1111-111111111111', 'Outdoor & Décor', 'Vintage Glass Dispensers with Taps', 'Various sizes 4–8l — each', 50, 5, 7),
('11111111-1111-1111-1111-111111111111', 'Outdoor & Décor', 'Glass Tear-Drop Dispensers with Taps', '9l each', 100, 2, 8),
('11111111-1111-1111-1111-111111111111', 'Outdoor & Décor', 'White Oval Serving Platters', 'Each', 20, 24, 9),
('11111111-1111-1111-1111-111111111111', 'Outdoor & Décor', 'Wedding Gift & Card Box', 'White painted rustic wood, 45×45cm', 50, 1, 10),
('11111111-1111-1111-1111-111111111111', 'Outdoor & Décor', 'Leather Vintage Suitcase (L)', 'For honeymoon fund, cards, gifts — each', 200, 2, 11),
('11111111-1111-1111-1111-111111111111', 'Outdoor & Décor', 'Gold Steel Signage Frame / Stand', '75cm (w) × 118cm (h)', 100, 1, 12),
('11111111-1111-1111-1111-111111111111', 'Bar Setup', 'White Bar Setup — INDOORS', 'Incl. bar, freezer, bins & crates', 700, 1, 13),
('11111111-1111-1111-1111-111111111111', 'Bar Setup', 'White Bar Setup — OUTDOORS', 'Incl. bar, freezer, bins, sink, pallet wall, 4 apple crates, fairy light curtain, signage', 950, 1, 14),
('11111111-1111-1111-1111-111111111111', 'Lighting', 'Fairy Light Curtains — Cool White', 'Like fresh starlight — each', 200, 2, 15),
('11111111-1111-1111-1111-111111111111', 'Lighting', 'Fairy Light Curtains — Warm White', 'Like candlelight — each', 200, 2, 16),
('11111111-1111-1111-1111-111111111111', 'Lighting', '40m Fairy Lights WW — Black Wire', 'Incl. outdoor setup with poles — each', 350, 4, 17),
('11111111-1111-1111-1111-111111111111', 'Lighting', '40m Fairy Lights WW — White Wire', 'Incl. indoor HALL AREA setup — each', 350, 2, 18),
('11111111-1111-1111-1111-111111111111', 'Lighting', '40m Fairy Lights WW — Green Wire', 'Incl. outdoor setup with poles', 350, 1, 19),
('11111111-1111-1111-1111-111111111111', 'Lighting', '2 × 25m Vintage Bistro / Festoon Lights', 'Delicate bistro string lights', 750, 1, 20),
('11111111-1111-1111-1111-111111111111', 'Lighting', 'Consol Solar Jar Lights', 'With Black Shepherd Crooks included — each', 30, 20, 21),
('11111111-1111-1111-1111-111111111111', 'Lighting', 'Shepherd Crooks', '14× low black, 6× tall white — each', 20, 20, 22),
('11111111-1111-1111-1111-111111111111', 'Chairs & Seating', 'White Stella Chairs', 'Each', 10, 130, 23),
('11111111-1111-1111-1111-111111111111', 'Chairs & Seating', 'Teak Benches — DRESSED', 'Incl. cushions & throws — each', 250, 6, 24),
('11111111-1111-1111-1111-111111111111', 'Chairs & Seating', 'Teak Benches — NAKED', 'Seats 3 — each', 200, 6, 25),
('11111111-1111-1111-1111-111111111111', 'Chairs & Seating', 'Park Bench at Pool — NAKED (if moved)', '2-seater — free if left in situ at pool', 150, 4, 26),
('11111111-1111-1111-1111-111111111111', 'Chairs & Seating', 'Park Bench at Pool — DRESSED', '2-seater incl. cushions & throws', 200, 4, 27),
('11111111-1111-1111-1111-111111111111', 'Chairs & Seating', 'Malawian Reed Chair — NAKED', 'Single, no adornment — each', 100, 8, 28),
('11111111-1111-1111-1111-111111111111', 'Chairs & Seating', 'Malawian Reed Chair — DRESSED', 'Incl. seat cushion & throw — each', 150, 8, 29),
('11111111-1111-1111-1111-111111111111', 'Chairs & Seating', 'Cane Patio Chairs — Dressed', 'Singles with cushion seat — each', 150, 9, 30),
('11111111-1111-1111-1111-111111111111', 'Chairs & Seating', 'Cane Patio Couch — Dressed', 'Double seater with cushion seat', 200, 1, 31),
('11111111-1111-1111-1111-111111111111', 'Hay Bales & Rustic', 'Picnic Benches (if moved)', 'Free in situ — R450 each if moved. 3 @ pool, 10 @ Erika', 450, 13, 32),
('11111111-1111-1111-1111-111111111111', 'Hay Bales & Rustic', 'Straw / Hay Bales', 'Incl. 3.6m whitewashed pine planks for seating — each', 25, 40, 33),
('11111111-1111-1111-1111-111111111111', 'Hay Bales & Rustic', 'Straw Bale Covers', 'Each covers 2 bales — price is for ALL 36 covers', 200, 36, 34),
('11111111-1111-1111-1111-111111111111', 'Comfort & Furnishings', 'Timbavati Mats (XL)', 'For picnics, bedouin seating — each', 250, 2, 35),
('11111111-1111-1111-1111-111111111111', 'Comfort & Furnishings', 'Cushions — Earth Tones & Geometrics', 'Price for ALL 20 cushions', 400, 20, 36),
('11111111-1111-1111-1111-111111111111', 'Comfort & Furnishings', 'Woven Throws / Picnic Blankets', 'Earth tones — price for ALL 30 throws', 400, 30, 37),
('11111111-1111-1111-1111-111111111111', 'Comfort & Furnishings', 'Malawian Reed Side Table / Coffee Table', 'Each', 90, 4, 38),
('11111111-1111-1111-1111-111111111111', 'Comfort & Furnishings', 'Linseed Oiled Tree Stumps', 'Various heights — each', 20, 20, 39),
('11111111-1111-1111-1111-111111111111', 'Fire & Heating', 'Fire Baskets — Full Setup', 'Incl. ~4 crates wood each', 450, 3, 40),
('11111111-1111-1111-1111-111111111111', 'Fire & Heating', 'Portable Half-Barrel Braais', 'Incl. braai equipment, cleaning, 2 bags wood, firelighters & charcoal', 350, 2, 41),
('11111111-1111-1111-1111-111111111111', 'Fire & Heating', 'Extra Firewood — Crate', 'For firepit & fire baskets', 60, 99, 42),
('11111111-1111-1111-1111-111111111111', 'Fire & Heating', 'Extra Firelighters', 'Per pack', 35, 99, 43),
('11111111-1111-1111-1111-111111111111', 'Fire & Heating', 'Extra Charcoal', 'For caterer / braais', 70, 99, 44),
('11111111-1111-1111-1111-111111111111', 'Fire & Heating', 'Extra Firewood — Bag', 'For braaing or fireplaces', 45, 99, 45),
('11111111-1111-1111-1111-111111111111', 'Fire & Heating', 'Patio Gas Heater', 'Incl. full gas cylinder & setup — each', 500, 3, 46),
('11111111-1111-1111-1111-111111111111', 'Kitchen & Utilities', 'Kitchen Fee — Under 90 Pax', 'Cleaning, gas, electricity, 1 scullery staff night shift (5–11pm)', 1000, 1, 47),
('11111111-1111-1111-1111-111111111111', 'Kitchen & Utilities', 'Kitchen Fee — Over 90 Pax', 'Cleaning, gas, electricity, 2 scullery staff night shift (5–11pm)', 1500, 1, 48),
('11111111-1111-1111-1111-111111111111', 'Kitchen & Utilities', 'Generators AVR', '7.5kVA & 8.5kVA incl. one tank of fuel each', 500, 2, 49),
('11111111-1111-1111-1111-111111111111', 'Kitchen & Utilities', 'Portable 4-Burner Gas Stove for Caterer', 'Incl. setup & gas', 400, 1, 50),
('11111111-1111-1111-1111-111111111111', 'Audio / Visual', 'HDTV Projector — Samsung Freestyle Gen 2', '1080P, incl. free screen — or project onto wall / hanging material', 1000, 1, 51),
('11111111-1111-1111-1111-111111111111', 'Audio / Visual', 'Portable PA System — JBL 320 Party Box', 'Bluetooth & rechargeable. Excl. microphones. Perfect for ceremony, M&G or after DJ', 1500, 1, 52),
('11111111-1111-1111-1111-111111111111', 'Audio / Visual', 'JBL Wireless Microphones (set of 2)', 'For use with JBL Party Box — vows, speeches', 250, 2, 53),
('11111111-1111-1111-1111-111111111111', 'Audio / Visual', 'Projector Screen — Parrot Portable', '', 250, 1, 54),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Bean Bag / Corn Hole Toss', '1 board & 2 sets of 5 beanbags per board — each', 100, 2, 55),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Beer Pong Table', 'Incl. setup (excl. beer)', 100, 1, 56),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Swing Ball Sets with Bats', 'Each', 75, 2, 57),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Giant Lawn Wooden O''s & X''s', '', 50, 1, 58),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Ring Toss', 'A-frame with pegs & 5 rope rings', 75, 1, 59),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Boule / Pétanque / Bocce', 'Each', 100, 2, 60),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Tabletop O''s & X''s (both sets)', 'Large wood on coffee table', 100, 2, 61),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Tabletop Dominoes (both sets)', 'Large wood on coffee table', 100, 2, 62),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Giant Jenga', 'In a box, setup on a crate table', 100, 1, 63),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Rugby Toss', 'Mini-rugby balls & wooden frame', 150, 1, 64),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Horse Shoe Toss & Metal Pegs', '', 75, 1, 65),
('11111111-1111-1111-1111-111111111111', 'Games & Entertainment', 'Croquet Sets (both)', 'Set for 4 players + set for 6 players', 175, 2, 66),
('11111111-1111-1111-1111-111111111111', 'Décor & Structures', 'Double Wooden Barn Doors in Frame', 'Setup on meadow', 650, 1, 67),
('11111111-1111-1111-1111-111111111111', 'Décor & Structures', 'Vintage Wooden Rustic Ladders (1.8m)', 'For décor, display, shelving — each', 150, 2, 68),
('11111111-1111-1111-1111-111111111111', 'Décor & Structures', 'Steel Curved Arch', 'Straight sides, round top — 255cm (h) × 154cm (w)', 250, 1, 69),
('11111111-1111-1111-1111-111111111111', 'Décor & Structures', 'Steel Round Wedding Arch', 'Fully round & circular — 2m (h) × 190cm across', 250, 1, 70),
('11111111-1111-1111-1111-111111111111', 'Extra Areas', 'Extra Area — Pool, Oak Tree & Hall', 'Areas other than Erika for M&G / Farewell Breakfast, plus kitchen fees', 2000, 1, 71),
('11111111-1111-1111-1111-111111111111', 'Extra Areas', 'Extra Area — Dam & Meadow', 'Any other areas other than Erika for M&G / Farewell Breakfast, plus kitchen fees', 2500, 1, 72),
('11111111-1111-1111-1111-111111111111', 'Extra Areas', 'Extra Area — Dam Wall, Jetty & Reservoir', '', 2500, 1, 73),
('11111111-1111-1111-1111-111111111111', 'Extra Areas', 'Extra Area — Poplar Forest', 'Incl. hay bale & plank seating', 2750, 1, 74),
('11111111-1111-1111-1111-111111111111', 'Extra Areas', 'Extra Area — Pine Forest', 'Excl. seating options', 2500, 1, 75),
('11111111-1111-1111-1111-111111111111', 'Extra Areas', 'Extra Area — Any Other Areas', 'Costs start at R2,500+', 2500, 1, 76),
('11111111-1111-1111-1111-111111111111', 'Extras & Add-ons', 'Additional Wedding Guests over 120', 'Per extra guest', 100, 999, 77),
('11111111-1111-1111-1111-111111111111', 'Extras & Add-ons', 'Additional M&G / Farewell Breakfast over 100', 'Per person', 50, 999, 78),
('11111111-1111-1111-1111-111111111111', 'Extras & Add-ons', 'Additional Onsite Campers', 'Own tents or glamping — R100 per person, per night', 100, 999, 79),
('11111111-1111-1111-1111-111111111111', 'Extras & Add-ons', 'Red Massey-Ferguson Tractor', 'Guest or bride & groom transport', 1000, 1, 80),
('11111111-1111-1111-1111-111111111111', 'Extras & Add-ons', 'Gorilla Carts (×2)', 'For service providers or guests', 200, 2, 81);

-- Accommodation rooms

insert into accommodation_rooms (venue_id, name, room_type, sleeps, price_per_night, description, sort_order) values
('11111111-1111-1111-1111-111111111111', 'Oak Cottage', 'Bridal Suite', 2, 0, 'Open-plan cottage with double bed, slipper bath, air con, walk-in shower, fireplace, stoep & braai. Situated right next to the Barn Venue and Wedding Meadow — the natural choice as a Bridal Suite.

Amenities: Double bed, Slipper bath, Walk-in shower, Air con, Fireplace, Stoep & braai, Next to Barn Venue', 0),
('11111111-1111-1111-1111-111111111111', 'Fig Cottage', 'Standard', 3, 0, 'Open-plan cottage with double bed, shower, and a single bed in an alcove off the lounge. Fireplace & braai. Suits a couple and a single, or two singles sharing.

Amenities: Double bed, Single bed alcove, Shower, Fireplace, Braai', 1),
('11111111-1111-1111-1111-111111111111', 'Quince Cottage', 'Standard', 4, 0, 'Separate bedroom with double bed, plus double bunk in a curtained alcove off the lounge for kids or young adults. Fireplace & braai. Part of the Family Lodge cluster.

Amenities: Double bed (bedroom), Double bunk (alcove), Fireplace, Braai', 2),
('11111111-1111-1111-1111-111111111111', 'Pine Cottage', 'Standard', 4, 0, 'Separate bedroom with two single beds, plus a double bed in an alcove off the open-plan lounge near the fireplace. Braai on the stoep. Part of the Family Lodge cluster.

Amenities: 2× single beds (bedroom), Double bed alcove, Fireplace, Braai on stoep', 3),
('11111111-1111-1111-1111-111111111111', 'Nightjar', 'Exclusive', 4, 0, 'Two-bedroom exclusive cottage with spa bath, walk-in shower, wood-fired hot tub, air con, hammocks, fireplace & braai. Queen bed + two ¾ beds. Situated near the Shop & Reception, fully self-catering.

Amenities: Queen bed, 2× ¾ beds, Spa bath, Walk-in shower, Wood-fired hot tub, Air con, Hammocks, Fireplace, Braai', 4),
('11111111-1111-1111-1111-111111111111', 'Hadeda', 'Exclusive', 4, 0, 'Two-bedroom exclusive cottage with spa bath, walk-in shower, wood-fired hot tub, air con, hammocks, fireplace & braai. Queen bed + double bed — perfect for two couples each with their own room.

Amenities: Queen bed, Double bed, Spa bath, Walk-in shower, Wood-fired hot tub, Air con, Hammocks, Fireplace, Braai', 5),
('11111111-1111-1111-1111-111111111111', 'Farmhouse Erika & Garden Flat', 'Farmhouse', 28, 0, 'The heart of the wedding — a large fully equipped farmhouse with 6 bedrooms (Rooms 1–6) plus a Garden Flat underneath the stoep with 2 bedrooms and a lounge that sleeps up to 5 more. 4 shared bathrooms. Bedding, linen & towels all included. Sleeps 23–28 guests total.

Amenities: 6 bedrooms + Garden Flat, 4 shared bathrooms (1 en-suite option in Room 3), Full kitchen, Multiple lounges, Front & back stoep, Baby cot in Room 3, Garden Flat with private bathroom, Electric blankets', 6),
('11111111-1111-1111-1111-111111111111', 'Africamps — Tent 1', 'Africamps', 5, 0, 'Nearest to pool & venue. Spacious safari tent, 2 bedrooms, bathroom with shower, air con, fireplace, kitchen, deck with braai. Double bed + double bed with single bunk above. Sleeps 2 couples or a family of 5.

Amenities: 2 bedrooms, Shower, Air con, Fireplace, Kitchen, Deck & braai, Closest to pool', 7),
('11111111-1111-1111-1111-111111111111', 'Africamps — Tent 2', 'Africamps', 5, 0, 'Spacious safari tent, 2 bedrooms, bathroom with shower, air con, fireplace, kitchen, deck with braai. Double bed + double bed with single bunk above.

Amenities: 2 bedrooms, Shower, Air con, Fireplace, Kitchen, Deck & braai', 8),
('11111111-1111-1111-1111-111111111111', 'Africamps — Tent 3', 'Africamps', 5, 0, 'Spacious safari tent, 2 bedrooms, bathroom with shower, air con, fireplace, kitchen, deck with braai. Double bed + double bed with single bunk above. Wi-Fi available.

Amenities: 2 bedrooms, Shower, Air con, Fireplace, Kitchen, Deck & braai, Wi-Fi', 9),
('11111111-1111-1111-1111-111111111111', 'Africamps — Tent 4', 'Africamps', 5, 0, 'Spacious safari tent, 2 bedrooms, bathroom with shower, air con, fireplace, kitchen, deck with braai. Double bed + double bed with single bunk above.

Amenities: 2 bedrooms, Shower, Air con, Fireplace, Kitchen, Deck & braai', 10),
('11111111-1111-1111-1111-111111111111', 'Africamps — Tent 5', 'Africamps', 5, 0, 'Spacious safari tent, 2 bedrooms, bathroom with shower, air con, fireplace, kitchen, deck with braai. Double bed + double bed with single bunk above. Wi-Fi available.

Amenities: 2 bedrooms, Shower, Air con, Fireplace, Kitchen, Deck & braai, Wi-Fi', 11),
('11111111-1111-1111-1111-111111111111', 'Africamps — Tent 6', 'Africamps', 5, 0, 'Spacious safari tent, 2 bedrooms, bathroom with shower, air con, fireplace, kitchen, deck with braai. Double bed + double bed with single bunk above.

Amenities: 2 bedrooms, Shower, Air con, Fireplace, Kitchen, Deck & braai', 12),
('11111111-1111-1111-1111-111111111111', 'Africamps — Tent 7', 'Africamps', 5, 0, 'Spacious safari tent, 2 bedrooms, bathroom with shower, air con, fireplace, kitchen, deck with braai. Double bed + double bed with single bunk above. Wi-Fi available.

Amenities: 2 bedrooms, Shower, Air con, Fireplace, Kitchen, Deck & braai, Wi-Fi', 13),
('11111111-1111-1111-1111-111111111111', 'Africamps — Tent 8', 'Africamps', 5, 0, 'Spacious safari tent, 2 bedrooms, bathroom with shower, air con, fireplace, kitchen, deck with braai. Double bed + double bed with single bunk above.

Amenities: 2 bedrooms, Shower, Air con, Fireplace, Kitchen, Deck & braai', 14),
('11111111-1111-1111-1111-111111111111', 'Africamps — Tent 9', 'Africamps', 5, 0, 'Spacious safari tent, 2 bedrooms, bathroom with shower, air con, fireplace, kitchen, deck with braai. Double bed + double bed with single bunk above.

Amenities: 2 bedrooms, Shower, Air con, Fireplace, Kitchen, Deck & braai', 15),
('11111111-1111-1111-1111-111111111111', 'Africamps — Tent 10', 'Africamps', 5, 0, 'Furthest from pool — most private. Spacious safari tent, 2 bedrooms, bathroom with shower, air con, fireplace, kitchen, deck with braai. Double bed + double bed with single bunk above.

Amenities: 2 bedrooms, Shower, Air con, Fireplace, Kitchen, Deck & braai, Most private', 16);

-- Suppliers attached to demo wedding

insert into suppliers (wedding_id, category, name, contact, cost, paid, notes) values
('22222222-2222-2222-2222-222222222222', 'Photography', 'Duane Smith Photography', '071 858 9653 · info@dsmith.co.za', 25000, false, 'Collection Two — Full Day Coverage. 9 hrs · 2 photographers · Wedding Timeline Assistance · On-site venue walkthrough · 1-week preview · 800+ edited HD images · Complimentary engagement shoot.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'Niki Events', 'Niki de Vries · 084 620 7703 · info@niki.events', NULL, false, 'Wedding Planning, Flowers & Décor. Based in Paarl.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'Ebb & Flow Events', 'Angela Millar · 082 310 6365 · info@ebbandflowevents.co.za', NULL, false, 'Flowers, Yoga & Event Management. LOCAL & ONSITE — based in Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'Nu Experiences', 'Margot · 083 259 1357 · events@nuexperiences.co.za', NULL, false, 'Excellent Coordinator & Planner. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'The Planner', 'Helmare vd Merwe · 079 898 9746 · info@metheplanner.co.za', NULL, false, 'Super Coordinator & Planner. LOCAL — Villiersdorp.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'The Event Planners', 'Niki Denner · 079 183 5006 · niki@theeventplanners.co.za', NULL, false, 'Coordinator & Planner. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'Heartistry', 'Nancy Hoepner · 078 893 4040 · nancy@heartistry-cpt.co.za', NULL, false, 'Excellent Coordinator & Planner. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'Flamboijant Events', 'Lizl Pieterse · 084 620 7703 · info@flamboijant.co.za', NULL, false, 'Coordinator & Planner, Décor, Furniture, Flowers & more. LOCAL — Bonnievale.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'Antoinette Events', 'Nikkie · 084 839 7137 · events@antoinetteevents.co.za', NULL, false, 'Coordinator & Planner, Décor, Furniture, Catering, Flowers & Utensils. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'Celeste Styled Events', 'Celeste Potgieter · 082 393 1239 · celeste@celestestyledevents.co.za', NULL, false, 'Coordinator & Planner. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'The Wedding Fairy', 'Rebecca Butler · 084 268 9881 · rebecca@theweddingfairy.co.za', NULL, false, 'Coordinator & Planner. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'Lavender Creations', 'Shannon Lavender · 082 924 7548 · shannon@lavendercreations.org', NULL, false, 'Planner & Coordinator. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'The Bloom Room', 'Cindy Du Toit · 072 240 6044 · cindy@thebloomroom.co.za', NULL, false, 'Coordinator, Planner, Flowers — also has musician & DJ contacts. George.'),
('22222222-2222-2222-2222-222222222222', 'Coordinator', 'Boutique Events', 'Ursula Forrest · 071 333 1111 · ursula@boutiqueevents.co.za', NULL, false, 'Luxury Weddings & Celebrations. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Catering', 'The Field Kitchen', 'Chef Darryl Burger · 076 711 2669 · darryl@thefieldkitchen.co.za', NULL, false, 'Excellent Private Chef — highly rated. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Catering', 'The Flying Pan', 'Chef Mathew Hoepner · 081 385 5589 / 078 055 6393 · info@theflyingpan.co.za', NULL, false, 'Excellent Catering & Chef. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Catering', 'Plum Kitchen', 'Di Doms · 082 560 3166 · di@plumkitchen.co.za', NULL, false, 'Superb & Top Class Local Caterer. LOCAL — Robertson. Note: generally closed mid-December to early January.'),
('22222222-2222-2222-2222-222222222222', 'Catering', 'Leeftijd Catering', 'Belia King · 072 169 6794 · info@leeftijd.co.za', NULL, false, 'Event, Wedding & Party Catering. LOCAL — from Montagu.'),
('22222222-2222-2222-2222-222222222222', 'Catering', 'Antoinette Events (Catering)', 'Nikkie · 084 839 7137 · events@antoinetteevents.co.za', NULL, false, 'Very Good Catering — also coordinates, plans & supplies décor & flowers. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Catering', 'YOYO Spitbraai', 'Jacques · 072 186 1381 · info@yoyospitbraais.co.za', NULL, false, 'Spitbraais, catering & more. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Catering', 'Lotus Food Truck & More', '072 128 6752 · info@lotusfoodtruck.co.za', NULL, false, 'Eastern inspired cuisine. Prefers to cook in venue kitchen due to distance. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Catering', 'Spit Braai Functions', 'Riaan & Jackie · 066 286 9938 / 076 123 0099 · info@spitbraaifunctions.co.za', NULL, false, 'Braai, Spitbraai & Potjiekos catering & events. Cape & Garden Route.'),
('22222222-2222-2222-2222-222222222222', 'Catering', 'Wynand Malan — SpitBraai', 'Wynand · 082 378 8778', NULL, false, 'Local Spitbraai Caterer, down to earth & affordable. LOCAL — Robertson. Great for Meet & Greet gathering.'),
('22222222-2222-2222-2222-222222222222', 'Food Trucks', 'Jack Rabbit', 'Marc & Vasti Vonk · 083 414 1181 / 079 885 4534 · vasti.jackrabbit@gmail.com', NULL, false, 'Brilliant Gourmet Burger Food Truck. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Food Trucks', 'Earth Fire Pizza', 'Melissa · 021 785 3560 · info@earthfirepizza.co.za', NULL, false, 'Fantastic Pizza Truck. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Food Trucks', 'Boulevard 82 Food Truck', 'Stan or Ryan · 074 252 0990 / 079 613 5041 · blvd82foods@gmail.com', NULL, false, 'Great Food Truck & Street Food. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Coffee & Drinks', 'The Blend Coffee & More', 'Benitha Gouws · 082 802 4843 · benithagouws@gmail.com', NULL, false, 'Gourmet Coffee. LOCAL — McGregor.'),
('22222222-2222-2222-2222-222222222222', 'Coffee & Drinks', 'L''Chaim Coffee — Robertson', '073 491 1687 · lchaimcoffee@gmail.com', NULL, false, 'Mobile Coffee Suppliers. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Coffee & Drinks', 'Plato Coffee VW Kombi', 'Roelof · 081 465 9947 · hello@plato.coffee', NULL, false, 'Mobile Coffee from a vintage VW Kombi. Western Cape.'),
('22222222-2222-2222-2222-222222222222', 'Coffee & Drinks', 'Hustle Ice Cream', 'Hadley Kent · 060 500 5797 · hustlecapetown@gmail.com', NULL, false, 'Premium Soft Serve Gelato. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Coffee & Drinks', 'Road Rage Coffee', 'Henry Britz · 076 203 8025 · roadragecoffee21@gmail.com', NULL, false, 'Gourmet Coffee. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Cakes & Desserts', 'Marinel Cakes', 'Marinel Nel · 083 372 1673', NULL, false, 'Local Cakes & Desserts. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Cakes & Desserts', 'Beswik Cakes', 'Bronwen Beswik · 071 869 7172 · bronbesbb@gmail.com', NULL, false, 'Local Cakes & Desserts. LOCAL — Bonnievale.'),
('22222222-2222-2222-2222-222222222222', 'Cakes & Desserts', 'Louretta''s Cake Boutique', '023 626 5133', NULL, false, 'Local Cakes, Bakes & Desserts. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Cakes & Desserts', 'Joyce DeWet — Special Event Cakes', 'Joyce De Wet · 079 524 0972 · joycedewet1@gmail.com', NULL, false, 'Local Cakes & Desserts. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Tents & Structures', 'The Tentmen', 'Ilse & Con Viljoen · 076 337 5407 / 082 775 8737 · thetentmen@gmail.com', NULL, false, 'BEST CHOICE for stretch tents, dance floor, great lights & more. LOCAL — Bonnievale.'),
('22222222-2222-2222-2222-222222222222', 'Tents & Structures', '4 Every Event', 'Nadia Strauss · 082 875 582 · nadia@4everyevent.co.za', NULL, false, 'Great Stretch tents, Furniture & Décor. Elgin.'),
('22222222-2222-2222-2222-222222222222', 'Tents & Structures', 'Best Events Tents & Décor', 'Sherylene · 023 004 0475 / 023 347 4923 · info@bestevents.co.za', NULL, false, 'Stretch tents, Furniture, Décor & Utensils. Worcester.'),
('22222222-2222-2222-2222-222222222222', 'Tents & Structures', 'Chattels', 'Anneke van Rhyn · 021 593 7705 · anneke@chattels.co.za', NULL, false, 'Marquee, Clearspan & Structures. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Tents & Structures', 'Downing Marquee Hire', '081 365 6777', NULL, false, 'Marquee, Clearspan & Structures. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Tents & Structures', 'Elite', 'Byron · 083 449 4612 · byron@marquees.co.za', NULL, false, 'Marquee, Clearspan & Structures. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Décor & Furniture', 'Flamboijant Events (Décor)', 'Lizl Pieterse · 084 620 7703 · info@flamboijant.co.za', NULL, false, 'Superb Décor, Flowers, Utensils, Glassware & more. LOCAL — Bonnievale.'),
('22222222-2222-2222-2222-222222222222', 'Décor & Furniture', 'Baie Goeters', 'Nicola Kaden · 067 784 3019 · enquiries@baiegoeters.co.za', NULL, false, 'Décor, Furniture, Utensils & More. Wellington.'),
('22222222-2222-2222-2222-222222222222', 'Décor & Furniture', '4 Every Event (Décor)', 'Nadia Strauss · 082 875 582 · nadia@4everyevent.co.za', NULL, false, 'Tents, Décor, Furniture & More. Elgin.'),
('22222222-2222-2222-2222-222222222222', 'Décor & Furniture', 'Ten of Cups', 'Eddie van Lamp · 079 696 5167 · admin@tenofcups.co.za', NULL, false, 'Décor, Furniture & Equipment. Stellenbosch.'),
('22222222-2222-2222-2222-222222222222', 'Décor & Furniture', 'Sitting Pretty Bespoke Event Design', '083 235 6282 / 082 687 9163 · hello@sitting-pretty.co.za', NULL, false, 'Décor, Furniture, Flowers & Equipment. Stellenbosch.'),
('22222222-2222-2222-2222-222222222222', 'Décor & Furniture', 'Best Events (Décor)', 'Sherylene · 023 004 0475 / 023 347 4923 · info@bestevents.co.za', NULL, false, 'Décor, Tents, Furniture & Utensils. Worcester.'),
('22222222-2222-2222-2222-222222222222', 'Glamping', 'Expedition Glamping', 'Camille or Rian · 079 928 3951 / 083 273 9905 · info@expeditionglamping.co.za', NULL, false, 'Excellent Bespoke Onsite Glamping in furnished Canvas Bell Tents. Note: R100 per camper per night venue fee applies.'),
('22222222-2222-2222-2222-222222222222', 'Glamping', 'You2Camp', 'Ryno Wade · 076 085 3696 · admin@you2camp.com', NULL, false, 'Various camping options with showers, bathrooms & catering. Note: R100 per camper per night venue fee applies.'),
('22222222-2222-2222-2222-222222222222', 'Glamping', 'Zulu Overland', 'Du Toit van Niekerk · 073 198 9992 · dutoit@zuluoverland.co.za', NULL, false, 'Onsite camping options. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Floristry', 'Flamboijant Events (Flowers)', 'Niki de Vries / Lizl Pieterse · 084 620 7703 · niki@flamboijant.co.za', NULL, false, 'Excellent Flowers, Décor, Planning, Utensils, Glassware & More. LOCAL — Bonnievale.'),
('22222222-2222-2222-2222-222222222222', 'Floristry', 'Ebb & Flow Events (Flowers)', 'Angela Millar · 082 310 6365 · info@ebbandflowevents.co.za', NULL, false, 'Flowers, Yoga & Event Management. LOCAL & ONSITE — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Floristry', 'Blommeprag', 'Anne-Marie · 082 378 3993 · lerouxs@barvallei.co.za', NULL, false, 'Local Flowers. LOCAL — Bonnievale.'),
('22222222-2222-2222-2222-222222222222', 'Floristry', 'Flowers By Arlene', 'Arlene Lloyd · 082 929 7054 · arlene@flowersbyarlene.co.za', NULL, false, 'Flowers. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Alcohol & Bar', 'Nomad Event Solutions', 'Gandre · 061 476 9143 · gandre@nomadevent.solutions', NULL, false, 'BEST OPTION for a Cash Bar! Includes on consignment stock, staff, liquor licence, tills, POS, credit card & more. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Alcohol & Bar', 'Grapevine — Blue Bottle Store', 'Jurgens Heyns · 082 378 3564 · jurgens@grapevineliquors.co.za', NULL, false, 'Great DIY option: bottle store including delivery & stock on consignment. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Alcohol & Bar', 'Saggy Stone Craft Beer, Gin & More', 'Jackie · 021 834 6300 · jackie@saggystone.co.za', NULL, false, 'Great Craft Beer, Craft Gin & more. LOCAL — Worcester.'),
('22222222-2222-2222-2222-222222222222', 'Alcohol & Bar', 'Pat Busch Reserve (ICE, WATER & MIXERS)', 'Lesley · 023 626 2033 · stay@patbusch.co.za', NULL, false, 'ICE, Waters, Cooldrinks & Mixers delivered. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Alcohol & Bar', 'Spar — Tops at Spar', 'Louise Blom · 023 626 1552 · robertson2@retail.spar.co.za', NULL, false, 'Bottle Store on consignment. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Alcohol & Bar', 'Vuilhond', 'Andre · 079 257 0570 · andre@vuilhond.co.za', NULL, false, 'Brandy on Tap.'),
('22222222-2222-2222-2222-222222222222', 'Waitrons & Staff', 'Nomad Event Solutions (Bar Staff)', 'Gandre · 061 476 9143 · gandre@nomadevent.solutions', NULL, false, 'Cash Bar — BEST OPTION! Incl. on consignment stock, staff, licence, tills, POS & more. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Waitrons & Staff', 'The Barmen Crew & More', 'Malcolm Donaldson · 082 474 1295 · malcolm36donaldson@gmail.com', 11050, false, 'RECOMMENDED: Waitrons & Bar staff. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Waitrons & Staff', 'Hero Events', 'Ludwig · 072 987 3542 · heroevents@gmail.com', NULL, false, 'Upmarket Waitrons & Bar Staff. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Waitrons & Staff', 'Saucy Events & Staffing', 'Rosemary · 068 321 3715 / 078 821 0858 · sauceyevents@gmail.com', NULL, false, 'Superb Waitrons & Bar Staff. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Waitrons & Staff', 'West Staff Services', 'Robert Van Noie · 084 885 7760 · info@weststaffservices.co.za', NULL, false, 'Waitrons & Bar Staff. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Waitrons & Staff', 'JT Events', 'Johan Potgieter · 076 509 7338 · jtevents@lantic.net', NULL, false, 'Waitrons & Bar Staff. Cape Region.'),
('22222222-2222-2222-2222-222222222222', 'Waitrons & Staff', 'Fernhout Staffing Services', 'Charlize Loois · 082 826 4140', NULL, false, 'Staffing (Bar & Waitrons). LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Bathrooms', 'Lookor', '072 672 446 · boland@lookor.com', NULL, false, 'Portable Lux Loos & Generators. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Bathrooms', 'Sales Hire', '021 931 2560 · toilets@saleshire.co.za', NULL, false, 'Portable Lux Loos & Shower Stalls. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Bathrooms', 'Boland Toilets', '086 111 5193 · info@jmgrp.co.za', NULL, false, 'Portable Lux Loos. Ceres.'),
('22222222-2222-2222-2222-222222222222', 'Generators', 'Robertson Tool Hire', '023 626 1618', NULL, false, 'Generators & more. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Generators', 'AH Marais', '023 626 3071 · info@ahm.co.za', NULL, false, 'Generators & more. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Generators', 'BreedeRivier Tool Hire', '023 626 1345 / 023 100 0943', NULL, false, 'Generators & more. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Marnel Toerien Make-Up Artist', 'Marnel Toerien · 072 337 3226 · info@marneltoerien.co.za', NULL, false, 'Make-Up Artist. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Candice Harker — Mobile Make-Up', 'Candice Harker · 078 476 1409 · candice@mobilemakeupartist.co.za', NULL, false, 'Make-Up Artist. Boland.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Make You Up', 'Jodine Swanepoel · 072 299 6704 · jodine@barvallei.co.za', NULL, false, 'Make-Up. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Madeleine Hair & Make-up', 'Madeleine · 084 812 5087 · info@madeleinehairandmakeup.co.za', NULL, false, 'Hair & Make-Up Artist. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Blusch Professional MakeUp', 'Mariette · 083 608 1141', NULL, false, 'Make-Up. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Illusions Hair Design', 'Cornel Hough · 071 241 4526 · cornelhough@live.co.za', NULL, false, 'Hair Stylist. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Isabeau Skincare Clinic', '072 406 4375 · info@isabeauskincareclinic.co.za', NULL, false, 'Local Skincare. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Glamourize Hair', 'Melissa Marais · 064 656 0222', NULL, false, 'Hair Stylist. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Maryna Kirsten Hair & MakeUp', 'Maryna Kirsten · 076 402 4218 · kirstenmaryna@gmail.com', NULL, false, 'Hair & Make-Up Artist. De Doorns.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Elizabeth Rae Hair & Make-Up', 'Elizabeth Rae · 082 452 9469 · elizabethraemua@gmail.com', NULL, false, 'Hair & Make-Up Artist. Rawsonville.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Suzette Erasmus Make-Up', 'Suzette Erasmus · 072 794 0164', NULL, false, 'Make-Up. LOCAL.'),
('22222222-2222-2222-2222-222222222222', 'Hair & Makeup', 'Candice Make-Up', 'Candice · 072 573 0771', NULL, false, 'Make-Up. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Ty and Eri Photo & Film', 'Tyron Mackensie · 074 870 6697 · info@tyanderi.com', NULL, false, 'Photography & Videos.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Andy & Szerdi Photography', 'Szerdi · 076 335 5708 · hello@andyandszerdi.com', NULL, false, 'Brilliant Photography. UK-based.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Lauren Pretorius Photography', 'Lauren Pretorius · 071 337 8840 · info@laurenpretoriusphotography.co.za', NULL, false, 'Excellent Photography.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Yeah Yeah Photography', 'Helena Krige · 083 260 0435 · helena@yeahyeah.co.za', NULL, false, 'Photography.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Lara Jess Photographer', 'Lara Thomas · 072 222 5170', NULL, false, 'Photography & Marriage Officiant. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Dillon Kin Photography', 'Dillon Kin · 084 730 8628 · hello@dillonkin.com', NULL, false, 'Photography. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Micke Creative', 'Micke · 073 609 5607 · hello@mickcreative.co.za', NULL, false, 'Photographer. Durbanville.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Vinyl Rae Photography', 'Kelly Rae Du Plooy · 071 526 3422 · vinylraephoto@gmail.com', NULL, false, 'Photography.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Sarah Isaacs Photography', 'Sarah & Oliver · 073 537 8290 · sarah@sarahisaacs.com', NULL, false, 'Excellent Photography. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Koringkriek Photography & Videos', 'Stefan Lous · 074 190 3796 / 083 424 1297 · stefan@koringkriek.com', NULL, false, 'Photography & Videos.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Helene Viljoen Photography', 'Helene Viljoen · 082 326 2679 · heleneviljoen@barvallei.co.za', NULL, false, 'Photography. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Kikito Photography', 'Skillie / Corrie · 084 840 0141 · motion@kikitography.com', NULL, false, 'Superb Photographer. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Light Lounge Studios', 'Nelis Engelbrecht · 084 205 6676 · info@nelisengelbrecht.co.za', NULL, false, 'Photography & Videos.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Michiel and Annie Wedding Films', 'Annie · 079 680 2014', NULL, false, 'Videography.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Orpen Film Co', 'Terrence Orpen · 083 555 4328 · hi@orpenfilms.co.za', NULL, false, 'Videography.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Mint Tea Photography', 'Sarah Da Silva · 083 323 4038 · sarahdasilva00@gmail.com', NULL, false, 'Photography.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Misha Lee Photography', 'Misha Lee Tame · 082 819 9079 · hello@mishalee.co.za', NULL, false, 'Photography.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Mustard Seed Films & Photography', 'Craig · 073 923 1112 · info@mustardseedfilms.co.za', NULL, false, 'Photography & Videos.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Nadine Aucamp Photography', 'Nadine Aucamp · 083 441 7630 · ndnaucamp@gmail.com', NULL, false, 'Photography.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Striped Fox Photography', 'Lee · 078 948 3282 · info@stripedfoxphotography.com', NULL, false, 'Photography. Paarl.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Teagan Smith Photography', 'Teagan Smith · 072 523 2838 · 4teagansmithphotography@gmail.com', NULL, false, 'Photography. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Photography', 'Zeven Media (Light + Lark)', 'Lindie van der Burgh · 060 786 2621 · chrisvdburgh@gmail.com', NULL, false, 'Photography & Videos.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'That DJ Guy', 'David Matfield · 071 643 7330 · dj@thatdjguy.co.za', NULL, false, 'Excellent DJ & Equipment.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Southern Sound', 'DJ U-One & Christelle Theron · 074 107 2885 · Southern.Sound.CPT@gmail.com', NULL, false, 'Sound & DJs.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Silk Music', 'Ryan Engelbrecht · 073 257 7612 · ryan@silkmusic.co.za', NULL, false, 'DJs, Music & Live Entertainment. Western Cape.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Shaza Live Entertainment', 'Shaza The Musician · 084 034 8006 · admin@shazamusic.co.za', NULL, false, 'Solo Live Entertainment, Drums & Vocals — EXCELLENT! RSA.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Simply Strings', 'Annemi Phillips · 079 528 9575 · annemi@simplystrings.co.za', NULL, false, 'Superb Strings Trio, various options & great audience participation.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'My Oh My Entertainment', 'Marne & Carla · 084 428 2195 / 071 609 1353 · info@myohmy.co.za', NULL, false, 'Various Brilliant live acts & musicians.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Christoff Beukes / ARK Music', 'Christoff Beukes · 073 306 6405', NULL, false, 'Musician, original live music & covers, DJ & Sound Equipment. George.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Sound Print Studio', 'Alaric von Molendorff · 083 996 9573 · alaric@soundprint.co.za', NULL, false, 'DJs & Equipment.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'DJ Dino Moran (DJ Top Hat)', 'mail@dinomoran.com', NULL, false, 'Renowned DJ & state of the art equipment.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'DJ Pepe', '', NULL, false, 'Mobile DJ.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Cape Town Jam', '084 568 0310 · capetownjambookings@gmail.com', NULL, false, 'DJs & Equipment.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Dynamic Sound', 'Mike Dickinson · 072 606 3131', NULL, false, 'Mobile DJ.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Empire Alight Band', 'Mark Mcree · 083 652 2566 · empirealight@gmail.com', NULL, false, 'Great 4 piece band.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'The DJ Company', '082 527 4968 · bookings@thedjcompany.co.za', NULL, false, 'Various DJ options.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Absolute Music', 'DJ Neil Dallas · 083 270 8234 · neil@absolutemusic.co.za', NULL, false, 'DJs & Juke Box options. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Music & DJ', 'Clued Up Entertainment', 'Scot · 082 295 1419 · scot@cluedupentertainment.co.za', NULL, false, 'Sound options, DJs, lighting and more.'),
('22222222-2222-2222-2222-222222222222', 'Officiants', 'I Do Weddings', 'Dion Goldie · 079 931 2427 / 083 800 6076 · enquiries@idoweddings.co.za', NULL, false, 'Marriage Officiant. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Officiants', 'Tie the Knot', 'Symi & Ava · 083 459 6859 / 083 305 8221 · ourday@tietheknotcapetown.co.za', NULL, false, 'Marriage Officiant. Grabouw.'),
('22222222-2222-2222-2222-222222222222', 'Officiants', 'Pierre Muller', 'Pierre Muller · 082 964 2909 · pinministries@gmail.com', NULL, false, 'Marriage Officiant. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Officiants', 'The Wedding Guy', 'John · 083 305 5441 · john@weddingguy.co.za', NULL, false, 'Marriage Officiant. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Officiants', 'Lara Marriage Officer', 'Lara Jess · 072 222 5170 · marriageofficerlara@gmail.com', NULL, false, 'Marriage Officiant & Photographer. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Officiants', 'Rupert De Koning', 'Rupert De Koning · 073 366 3777', NULL, false, 'NG Kerk. LOCAL — Montagu.'),
('22222222-2222-2222-2222-222222222222', 'Officiants', 'DS Marius Joubert', 'Marius Joubert · 082 557 5985', NULL, false, 'LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Officiants', 'Hello Marriage Officer', 'Kobus Massyn · 083 353 5678 · info@hello-marriageofficer.co.za', NULL, false, 'Helderberg.'),
('22222222-2222-2222-2222-222222222222', 'Officiants', 'Heila Downey SSN', 'Heila Downey · 023 626 3515 · heila.downey@gmail.com', NULL, false, 'Non-denominational. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Officiants', 'Troy Marriage Officer', 'Troy Goldie · 082 852 4571 / 021 930 5119 · weddings@telkomsa.net', NULL, false, 'Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Insurance', 'I Do Insure', 'Melissa Kloppers · 011 312 6784 · melissa@idoinsure.co.za', NULL, false, 'Wedding Insurance Cover: Peace of Mind for nearly any eventuality with regards to your celebration. JHB / Online.'),
('22222222-2222-2222-2222-222222222222', 'Transport', 'Robertson Transfers', '076 126 1867', NULL, false, 'Personalised Transfer Service — airport transfers & more. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Transport', 'Vintage Cars — Montagu Hotel', '023 614 3125 · res@montagucountryhotel.co.za', NULL, false, 'Vintage Cars for the wedding. Montagu.'),
('22222222-2222-2222-2222-222222222222', 'Transport', 'Route Runners', 'Hennie Botha · 076 938 2837 · henniebotha08@gmail.com', NULL, false, 'Wedding Transfers, airport, wine tours. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Transport', 'Swannies Bus Services', '023 111 0006', NULL, false, 'Bus Service. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Transport', 'Van Schoor Shuttles', '082 678 1142', NULL, false, 'Shuttle Service. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Transport', 'Piet Pompies', 'Piet Pompies · 072 115 5895', NULL, false, 'Transfers. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Transport', 'Rob Visagie Taxis', 'Rob Visagie · 082 592 1451 · visagieeunice25@gmail.com', NULL, false, 'Taxis & Transfers. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Transport', 'Die Bus — Robertson', 'J.D. Cotze · 081 369 3405 / 071 879 9394 · diebus22@gmail.com', NULL, false, 'Bus Service. LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Child Minders', 'Robertson Hospice', '023 626 5710', NULL, false, 'Contact directly for a list of trained & vetted local childcare professionals with experience (first aid etc.). LOCAL — Robertson.'),
('22222222-2222-2222-2222-222222222222', 'Child Minders', 'Holiday Nannies', 'Alicia · 082 573 9200 · info@holidaynannies.co.za', NULL, false, 'Various Nannies & Childminders. Cape Town.'),
('22222222-2222-2222-2222-222222222222', 'Child Minders', 'Winelands Nannies', 'Sue · sue@winelandnannies.com', NULL, false, 'Various Nannies & Childminders. Franschhoek.');

-- Day-of timeline

insert into timeline_items (wedding_id, starts_at, label, description, sort_order) values
('22222222-2222-2222-2222-222222222222', '14:00:00', '[MG] Check-in Opens', 'Guests arrive and check into their cottages and Africamps tents. · Reception / Farmhouse Erika', 0),
('22222222-2222-2222-2222-222222222222', '16:00:00', '[MG] Welcome Drinks on the Terrace', 'Sundowners, snacks and lawn games. Relaxed meet-and-greet for the full wedding party. · The Dam Terrace', 1),
('22222222-2222-2222-2222-222222222222', '18:00:00', '[MG] Braai & Pre-Wedding Dinner', 'Casual outdoor braai. Salads, sides and dessert provided. · The Farmhouse Garden', 2),
('22222222-2222-2222-2222-222222222222', '20:00:00', '[MG] Bonfire & Acoustic Music', 'Acoustic set or playlist around the fire. Stars over the Robertson valley. · The Fire Pit Area', 3),
('22222222-2222-2222-2222-222222222222', '22:00:00', '[MG] Bar Closes — Early Night', 'Early night — big day tomorrow! · Farmhouse Erika', 4),
('22222222-2222-2222-2222-222222222222', '10:00:00', '[WED] Bridal Party Arrives & Prep Begins', 'Hair, makeup and getting ready. Champagne breakfast served. · The Farmhouse', 5),
('22222222-2222-2222-2222-222222222222', '12:00:00', '[WED] Photographer & Videographer Arrive', 'Getting ready shots, detail photos, dress and rings. · The Farmhouse', 6),
('22222222-2222-2222-2222-222222222222', '13:00:00', '[WED] Groom & Groomsmen Arrive', 'Final prep, buttonholes, group photos. · The Barn Suite', 7),
('22222222-2222-2222-2222-222222222222', '13:30:00', '[WED] Guests Begin Arriving', 'Welcome drinks served at the terrace. · Main Entrance', 8),
('22222222-2222-2222-2222-222222222222', '14:00:00', '[WED] Ceremony Begins', 'Guests seated 15 minutes before. Processional music cued. · Ceremony Arch — Lakeside', 9),
('22222222-2222-2222-2222-222222222222', '14:45:00', '[WED] Cocktail Hour', 'Canapés, welcome drinks, lawn games. Couple away for portraits. · The Dam Terrace', 10),
('22222222-2222-2222-2222-222222222222', '15:00:00', '[WED] Couple Portraits', 'Photographer leads couple through the fynbos and vineyard for golden-hour portraits. · Around the Reserve', 11),
('22222222-2222-2222-2222-222222222222', '16:30:00', '[WED] Reception Hall Opens', 'Guests invited inside. Background music plays. Table seating. · The Barn — Reception', 12),
('22222222-2222-2222-2222-222222222222', '17:00:00', '[WED] Welcome & Speeches', 'MC welcome, father of bride, best man, matron of honour. · Reception', 13),
('22222222-2222-2222-2222-222222222222', '18:00:00', '[WED] Dinner Served', 'Three-course sit-down dinner. Background playlist. · Reception', 14),
('22222222-2222-2222-2222-222222222222', '19:30:00', '[WED] Cake Cutting', 'Cake cutting ceremony. Dessert & coffee served. · Reception', 15),
('22222222-2222-2222-2222-222222222222', '20:00:00', '[WED] First Dance', 'Couple first dance, then parent dances. DJ takes over. · Dance Floor', 16),
('22222222-2222-2222-2222-222222222222', '20:30:00', '[WED] Dancing & Celebrations', 'Open dance floor. DJ set. Bar open. · Dance Floor', 17),
('22222222-2222-2222-2222-222222222222', '23:00:00', '[WED] Last Dance & Send-Off', 'Sparkler send-off. Couple retired to Honeymoon Suite. · Main Entrance', 18),
('22222222-2222-2222-2222-222222222222', '08:00:00', '[FB] Farewell Breakfast Served', 'Full breakfast spread — eggs, toast, fruit, coffee & juice for all guests. · The Farmhouse — Stoep', 19),
('22222222-2222-2222-2222-222222222222', '09:30:00', '[FB] Final Toasts & Memories', 'A short toast to the newlyweds. Share your favourite moments. · The Stoep', 20),
('22222222-2222-2222-2222-222222222222', '11:00:00', '[FB] Check-out & Farewell', 'All guests to vacate rooms by 11:00. Safe travels to everyone! · Main Entrance', 21);

